### PR TITLE
Unit Test

### PR DESCRIPTION
**Pull request by sshiraiwa**
This pull request add a unit test script.
The script runs examples in the example directory and compares the output with corresponding c++
version example.
It compares numbers which appears in two outputs and checks if there are significant difference or not.
The script ignores some of less important numbers such as CPU time and Newton iteration errors.

Python examples are modified so that it runs at the same input parameters as C++ version if it runs with no command line arguments.
Note that some of python examples does not have a proper argument parser yet.

### CODE REVIEW

**Comment by sshiraiwa** [comment]
Here is a screen capture of running test.py

unit_test_pymfem

**Comment by tzanio** [comment]
Looks, nice Syun'ichi!

**Comment by sshiraiwa** [comment]
Thank you for your comment. Here is a full test result obtained on MIT's new cluster.

*  The most of the outputs agree very well. 
*  In ex4 and ex13p, the number of iteration taken to converge is different. However, final L2 error (ex4) and the eigenvalue (ex13p) are the same.
*  ex10 and ex10p show small differences of |r| during the newton iteration process.
*  ex7p also shows small rational difference of L2 error.

All of these small differences don’t seem significant and relating to an iterative solver used in examples.  It may be due to the difference of initial condition of solution vector. However, it is not clear to me how and why it can be different.

BTW, ex9 and ex16 do not print really useful information to compare. They only print time stepping information. It would be useful if they print out some physical number derived from a solution. 

The test module also compares the execution time, but it is not really measuring an execution time alone. It includes all other things such as the time spend for Python interpreter launch and dynamic library loading. Nonetheless, in the examples that take long time, such as ex10, ex15 and ex15p, Python version took about from x1 to x2 of C++. Not too bad ,,,, I suppose.

[test_out.txt](https://github.com/mfem/PyMFEM/files/847481/test_out.txt)

**Comment by tzanio** [comment]
Ok, thanks.

These differences are not too surprising and we will consider adding better output for comparing in examples 9 and 16.

Time difference of x1 to x2 is not bad at all, IMHO!

**Pull request merged**
