### PR TITLE
Workflows

### PR DESCRIPTION
**Pull request by justinlaughlin**
**Do not merge**

I'm trying to test a workflow file but according to what I've read on stack exchange, github needs a pull request to register the workflow before it can be triggered manually.

https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo

### CODE REVIEW

**Comment by sshiraiwa** [comment]
Merging this PR. The build error with MFEM master will be address in next PR.

**Comment by sshiraiwa** [comment]
Well. I noticed it is still in draft mode. @justinlaughlin, please confirm that it is ready to review and merge.

**Comment by justinlaughlin** [comment]
It is ready to merge - does it still say draft mode? I'll add in the option for triggering off of base MFEM in a separate branch.

**Review by sshiraiwa — APPROVED** [review]
Thank you for the improvement. I will merge this. I suppose that some test with master will still fail because ex18/ex18p were updated. Otherwise, it should go through. Let's see.

**Pull request merged**
