### PR TITLE
Fix mesh calls in tests

### PR DESCRIPTION
**Pull request by IdoAkkerman**
This PR fixes a small issue in the tests.  Instead of `Mesh_` memberfunctions are called using `Mesh`

### CODE REVIEW

**Comment by sshiraiwa** [comment]
Hi @IdoAkkerman, thank you for this PR. 
Somehow, the test using current MFEM master is failing. But, this is not due to this PR. 
I will take a look later

**Review by sshiraiwa — APPROVED** [review]
Thank you for this fix

**Comment by sshiraiwa** [comment]
It turns out hat this commit on MFEM was a cause of test error here.
https://github.com/mfem/mfem/commit/c3dbd8041b0c2345756e508a5c5139d77973d3d4

I will merge this and overwrite it with a fix

**Comment by v-dobrev** [comment]
> It turns out hat this commit on MFEM was a cause of test error here. [mfem/mfem@c3dbd80](https://github.com/mfem/mfem/commit/c3dbd8041b0c2345756e508a5c5139d77973d3d4)

Hi @sshiraiwa, can you elaborate: what issue did this mfem commit cause?

Is there some relatively basic test for pymfem that we can add to mfem's CI -- maybe we can catch and fix pymfem issues like this earlier.

**Comment by sshiraiwa** [comment]
@v-dobrev 
The issue was MFEM_EXPORT macro newly used in some header file. 
And, yes, I think it is time to add some basic CI test when something new is merged in mfem master. We are now dynamically generating the wrapper codes. Thus it is easy to catch this kind of side effects, if mfem CI runs basic 
test. We can discuss how and what to test off-line.

**Pull request merged**
